services: 
  grpc-server: 
    build: ./grpc-server 
    container_name: grpc-server 
    ports: 
      - "50051:50051" 
    volumes: 
      - grpc-server:/app/media 
      - ./data/media:/app/media 
    environment: 
      - GRPC_SERVER_PORT=50051 
      - MAX_WORKERS=10 
      - MEDIA_PATH=/app/media 
      - DBNAME=mydatabase 
      - DBUSERNAME=myuser 
      - DBPASSWORD=mypassword 
      - DBHOST=db 
      - DBPORT=5432 
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PW=password
    depends_on: 
      - db 
  
  rest-api-server:
      build: ./rest_api_server 
      container_name: rest_api_server 
      ports: 
          - "8000:8000"
      volumes: 
          - ./data/media:/app/media 
      environment: 
          - GRPC_PORT=50051 
          - GRPC_HOST=grpc-server 
          - DBNAME=mydatabase 
          - DBUSERNAME=myuser 
          - DBPASSWORD=mypassword 
          - DBHOST=db 
          - DBPORT=5432
      depends_on:
          - grpc-server
          - db
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  db:
    image: postgres:latest 
    container_name: postgres-db 
    environment: 
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: mydatabase 
    ports: 
      - "5432:5432" 
    volumes: 
      - pgdata:/var/lib/postgresql/data  

  worker:
    build : ./worker-rabbit-csv
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      - db
      - grpc-server
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PW=password
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    
  graphql-server:
    build: ./graphql-server
    container_name: graphql-server
    ports:
      - "9000:9000"
    volumes:
      - ./graphql-server:/app
    environment:
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db
  
  frontend:
    build: ./is-frontend-template
    container_name: frontend
    ports:
      - "3000:3000" 
    environment:
      - REST_API_BASE_URL=http://rest-api-server:8000
      - GRAPHQL_API_BASE_URL=http://graphql-server:9000
    depends_on:
      - rest-api-server
      - graphql-server
volumes: 
  grpc-server: 
  pgdata: