# Generated by Django 4.2.17 on 2024-12-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
    ]
