# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_services.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server_services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_services.proto\x12\x0fserver_services\"I\n\x13SendFileRequestBody\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x11\n\tfile_mime\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\"\'\n\x14SendFileResponseBody\x12\x0f\n\x07success\x18\x01 \x01(\x08\"8\n\x0f\x43svToXmlRequest\x12\x10\n\x08\x63sv_file\x18\x01 \x01(\x0c\x12\x13\n\x0bschema_path\x18\x02 \x01(\t\"8\n\x10\x43svToXmlResponse\x12\x13\n\x0bxml_content\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x14XmlValidationRequest\x12\x10\n\x08xml_file\x18\x01 \x01(\x0c\"8\n\x15SendFileChunksRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\":\n\x16SendFileChunksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x10XmlFilterRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0bxpath_query\x18\x02 \x01(\t\"5\n\x11XmlFilterResponse\x12\x0f\n\x07results\x18\x01 \x03(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x17\x45xportToDatabaseRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"<\n\x18\x45xportToDatabaseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbd\x04\n\x0fSendFileService\x12W\n\x08SendFile\x12$.server_services.SendFileRequestBody\x1a%.server_services.SendFileResponseBody\x12V\n\x0fProcessCsvToXml\x12 .server_services.CsvToXmlRequest\x1a!.server_services.CsvToXmlResponse\x12W\n\x0bValidateXml\x12%.server_services.XmlValidationRequest\x1a!.server_services.CsvToXmlResponse\x12\x63\n\x0eSendFileChunks\x12&.server_services.SendFileChunksRequest\x1a\'.server_services.SendFileChunksResponse(\x01\x12R\n\tFilterXml\x12!.server_services.XmlFilterRequest\x1a\".server_services.XmlFilterResponse\x12g\n\x10\x45xportToDatabase\x12(.server_services.ExportToDatabaseRequest\x1a).server_services.ExportToDatabaseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDFILEREQUESTBODY']._serialized_start=42
  _globals['_SENDFILEREQUESTBODY']._serialized_end=115
  _globals['_SENDFILERESPONSEBODY']._serialized_start=117
  _globals['_SENDFILERESPONSEBODY']._serialized_end=156
  _globals['_CSVTOXMLREQUEST']._serialized_start=158
  _globals['_CSVTOXMLREQUEST']._serialized_end=214
  _globals['_CSVTOXMLRESPONSE']._serialized_start=216
  _globals['_CSVTOXMLRESPONSE']._serialized_end=272
  _globals['_XMLVALIDATIONREQUEST']._serialized_start=274
  _globals['_XMLVALIDATIONREQUEST']._serialized_end=314
  _globals['_SENDFILECHUNKSREQUEST']._serialized_start=316
  _globals['_SENDFILECHUNKSREQUEST']._serialized_end=372
  _globals['_SENDFILECHUNKSRESPONSE']._serialized_start=374
  _globals['_SENDFILECHUNKSRESPONSE']._serialized_end=432
  _globals['_XMLFILTERREQUEST']._serialized_start=434
  _globals['_XMLFILTERREQUEST']._serialized_end=492
  _globals['_XMLFILTERRESPONSE']._serialized_start=494
  _globals['_XMLFILTERRESPONSE']._serialized_end=547
  _globals['_EXPORTTODATABASEREQUEST']._serialized_start=549
  _globals['_EXPORTTODATABASEREQUEST']._serialized_end=593
  _globals['_EXPORTTODATABASERESPONSE']._serialized_start=595
  _globals['_EXPORTTODATABASERESPONSE']._serialized_end=655
  _globals['_SENDFILESERVICE']._serialized_start=658
  _globals['_SENDFILESERVICE']._serialized_end=1231
# @@protoc_insertion_point(module_scope)
